package rnikolaus.finddoubleclasses;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author rapnik
 */
public class SummarizerTreePanel extends javax.swing.JPanel {

    /**
     * Creates new form SummarizerTreePanel
     */
    public SummarizerTreePanel() {
        initComponents();
    }
    public void displaySummarizer(Summarizer summarizer){
        jTree1.setModel(buildTreeModel(summarizer));
        jTree1.repaint();
    }
    private DefaultTreeModel buildTreeModel(Summarizer summarizer) {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode();
        DefaultTreeModel result = new DefaultTreeModel(root);
        for (String jarentry: summarizer.getMultipleEntries()){
            if (jarentry.endsWith("/"))continue;
            DefaultMutableTreeNode jarEntryNode = new DefaultMutableTreeNode(jarentry);
            root.add(jarEntryNode);
            for (String locations:summarizer.getLocations(jarentry)){
                DefaultMutableTreeNode locationNode = new DefaultMutableTreeNode(locations);
                jarEntryNode.add(locationNode);
            }
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setRootVisible(false);
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
